name: Site Deploy
on:
  # The workflow_run event only triggers if the workflow file is on the default branch.
  workflow_run:
    workflows: ["Site Test"]
    #branches: [main]
    types:
      - completed

jobs:
  deploy:
    # Only run if above workflow was successful.
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Load node version from .nvmrc
        run: echo "NODE_VERSION=$(cat ./website/.nvmrc)" >> $GITHUB_ENV
      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install & Test
        working-directory: ./website
        run: npm install
      - name: Build
        working-directory: ./website
        run: npm run predeploy  # The predeploy script runs build & performs any special preperations for GitHub pages.
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./website/build
            publish_branch: gh-pages
