name: Site Deploy
on:
  workflow_dispatch:  # Allow manual dispatching of this workflow.
  workflow_run: # The workflow_run event only triggers if the workflow file is on the default branch.
    branches: [main]
    workflows: ["Site Test"]
    types:
      - completed

jobs:
  deploy:
    # Only run if this is not caused by a workflow_run, or if it is from workflow_run, if the conclusion of the last workflow was success.
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v3
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}  # Trigger GitHub Deployments
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: fb515be51650a4b329622e852ccbed27
          projectName: ps2iodb
          directory: dist
          workingDirectory: website
