name: Build Extractor (Linux)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.7

      - name: Install system dependencies for wxPython
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-wxgtk4.0

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wxPython PyOpenGL Pillow

      - name: Run build script
        run: |
          cd extractor
          chmod +x build.sh
          ./build.sh

      - name: Upload built artifact
        uses: actions/upload-artifact@v4
        with:
          name: PS2IODB-Extractor
          path: extractor/dist/PS2IODB\ Extractor
