name: Build Extractor (macOS arm64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.7

      - name: Install UPX (for PyInstaller compression)
        run: |
          brew install upx

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U wxPython  # macOS (like Windows) doesn't need the linux-specific wxPython URL for pre-built wheel binaries. https://wxpython.org/pages/downloads/index.html
          pip install PyOpenGL Pillow pyinstaller

      - name: Run build script
        run: |
          cd extractor
          chmod +x build.sh
          ./build.sh

      - name: Upload built artifact
        uses: actions/upload-artifact@v4
        with:
          name: PS2IODB-Extractor
          path: extractor/dist/PS2IODB\ Extractor
