name: Site Build/Test

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: List files at root
      run: ls -a
    - name: List files inside Site
      run: ls -a
      working-directory: ./website
    - name: Load node version from .nvmrc
      run: echo "NODE_VERSION=$(cat ./website/.nvmrc)" >> $GITHUB_ENV
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Build and Test
      working-directory: ./website
      run: |
        npm ci
        npm run build
